import Image from "next/image";
import { Document } from "@/lib/api";
import { MoneyAmount } from "@/components/money-amount";

export function DocumentView({ document }: { document: Document }) {
  return <div className="print-document-shell"><header className="print-document-header"><div><Image src="/daftar-primary.svg" width={224} height={78} alt="Daftar" /><p>Financial document</p></div><div><span>Finalized</span><strong>{document.reference}</strong><time dateTime={document.finalizedAt ?? undefined}>{document.finalizedAt ? formatTimestamp(document.finalizedAt) : ""}</time></div></header><div className="print-document-title"><p>Prepared for</p><h1>{document.customer}</h1><h2>{document.title}</h2></div><div className="document-view"><section className="editor-card view-document"><div className="view-metadata"><div><span>Customer</span><strong>{document.customer}</strong></div><div><span>Issue date</span><strong>{formatDate(document.issueDate)}</strong></div><div><span>Currency</span><strong>{document.currency}</strong></div><div><span>Reference</span><strong className="document-reference">{document.reference}</strong></div></div>
    <div className="view-lines"><div className="view-line view-line--head"><span>Description</span><span>Qty</span><span>Unit price</span><span>Discount</span><span>Tax</span><span>Total</span></div>{document.lineItems.map((line) => <div className="view-line" key={line.id}><strong>{line.description}</strong><span>{line.quantity}</span><span>{document.currency} {line.unitPrice}</span><span>{line.discount ? `${line.discount.value}${line.discount.type === "percentage" ? "%" : ` ${document.currency}`}` : "—"}</span><span>{line.taxRate}%</span><strong>{document.currency} {line.calculated.lineTotal}</strong></div>)}</div>
  </section><aside className="calculation-card view-summary"><p className="eyebrow">Final totals</p><h2>{document.reference}</h2><dl className="totals-list"><div><dt>Subtotal</dt><dd><MoneyAmount amount={document.totals.subtotal} currency={document.currency} /></dd></div><div><dt>Discount</dt><dd>− <MoneyAmount amount={document.totals.discount} currency={document.currency} /></dd></div><div><dt>Tax</dt><dd><MoneyAmount amount={document.totals.tax} currency={document.currency} /></dd></div><div className="grand-total"><dt>Grand total</dt><dd><MoneyAmount amount={document.totals.grandTotal} currency={document.currency} /></dd></div></dl><div className="tax-summary"><h3>Tax breakdown</h3>{document.taxBreakdown.map((tax) => <div key={tax.rate}><span>{tax.rate}% on {document.currency} {tax.taxableAmount}</span><strong>{document.currency} {tax.taxAmount}</strong></div>)}</div></aside></div><footer className="print-document-footer"><span>Calculated by Daftar</span><span>{document.calculationPolicyVersion ?? "Server-calculated totals"}</span></footer></div>;
}

function formatDate(value: string) { return new Intl.DateTimeFormat("en", { dateStyle: "long", timeZone: "UTC" }).format(new Date(`${value.slice(0, 10)}T00:00:00Z`)); }
function formatTimestamp(value: string) { return new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short", timeZone: "UTC" }).format(new Date(value)); }
