package service

import (
	"context"
	"reflect"
	"testing"
	"time"

	"github.com/babafemi99/daftar/backend/internal/buhari"
	"github.com/babafemi99/daftar/backend/internal/calculations"
	"github.com/babafemi99/daftar/backend/internal/mercury"
	"github.com/babafemi99/daftar/backend/internal/model"
	"github.com/babafemi99/daftar/backend/internal/pkg/lid"
	"github.com/babafemi99/daftar/backend/internal/pkg/requestctx"
)

func TestDocumentServiceAddLine(t *testing.T) {
	service, repository, ctx := newLineService(t, 1)
	result, err := service.AddLine(ctx, repository.document.ID, 1, calculations.LineInput{
		ID: "client-selected-id", Description: "Added", Quantity: 2, UnitPriceMinor: 500, TaxRate: 100_000,
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(result.LineItems) != 2 || result.Version != 2 || result.Totals.GrandTotalMinor != 2_100 {
		t.Fatalf("unexpected updated document: lines=%d version=%d totals=%+v", len(result.LineItems), result.Version, result.Totals)
	}
	if result.LineItems[1].ID == "client-selected-id" || lid.Validate(result.LineItems[1].ID, lid.Line) != nil {
		t.Fatalf("line ID was not generated by the server: %q", result.LineItems[1].ID)
	}
}

func TestDocumentServiceAddInvalidLineDoesNotPersist(t *testing.T) {
	service, repository, ctx := newLineService(t, 1)
	before := repository.document
	_, err := service.AddLine(ctx, repository.document.ID, 1, calculations.LineInput{Description: "Invalid", Quantity: 0})
	if !hasCode(err, buhari.CodeValidationFailed) {
		t.Fatalf("error = %v", err)
	}
	if repository.replaceCalls != 0 || repository.document.Version != before.Version || len(repository.document.LineItems) != len(before.LineItems) {
		t.Fatal("invalid line changed the stored document")
	}
}

func TestDocumentServiceRejectsLineBeyondLimit(t *testing.T) {
	service, repository, ctx := newLineService(t, calculations.MaxLineItems)
	_, err := service.AddLine(ctx, repository.document.ID, 1, calculations.LineInput{Description: "Overflow", Quantity: 1})
	if !hasCode(err, buhari.CodeValidationFailed) || repository.replaceCalls != 0 {
		t.Fatalf("error=%v replaceCalls=%d", err, repository.replaceCalls)
	}
}

func TestDocumentServiceUpdateLinePreservesIDAndRecalculates(t *testing.T) {
	service, repository, ctx := newLineService(t, 1)
	lineID := repository.document.LineItems[0].ID
	result, err := service.UpdateLine(ctx, repository.document.ID, lineID, 1, calculations.LineInput{
		ID: lid.NewLine(), Description: "Updated", Quantity: 3, UnitPriceMinor: 1_000,
	})
	if err != nil {
		t.Fatal(err)
	}
	if result.LineItems[0].ID != lineID || result.LineItems[0].Description != "Updated" || result.Totals.GrandTotalMinor != 3_000 || result.Version != 2 {
		t.Fatalf("unexpected update: %+v", result)
	}
}

func TestDocumentServiceUpdateAndDeleteMissingLine(t *testing.T) {
	service, repository, ctx := newLineService(t, 1)
	missingID := lid.NewLine()
	if _, err := service.UpdateLine(ctx, repository.document.ID, missingID, 1, calculations.LineInput{}); !hasCode(err, buhari.CodeNotFound) {
		t.Fatalf("update error = %v", err)
	}
	if _, err := service.DeleteLine(ctx, repository.document.ID, missingID, 1); !hasCode(err, buhari.CodeNotFound) {
		t.Fatalf("delete error = %v", err)
	}
	if repository.replaceCalls != 0 {
		t.Fatalf("replace calls = %d", repository.replaceCalls)
	}
}

func TestDocumentServiceDeleteLineIncludingFinalLine(t *testing.T) {
	service, repository, ctx := newLineService(t, 2)
	firstID := repository.document.LineItems[0].ID
	result, err := service.DeleteLine(ctx, repository.document.ID, firstID, 1)
	if err != nil || len(result.LineItems) != 1 || result.Version != 2 {
		t.Fatalf("first delete lines=%d version=%d error=%v", len(result.LineItems), result.Version, err)
	}
	lastID := result.LineItems[0].ID
	result, err = service.DeleteLine(ctx, repository.document.ID, lastID, 2)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.LineItems) != 0 || result.Totals != (calculations.Totals{}) || len(result.TaxBreakdown) != 0 || result.Version != 3 {
		t.Fatalf("final-line delete did not produce an empty calculated draft: %+v", result)
	}
}

func TestDocumentServiceLineMutationLifecycleAndOwnership(t *testing.T) {
	t.Run("finalized", func(t *testing.T) {
		service, repository, ctx := newLineService(t, 1)
		if err := repository.document.Finalize(time.Now().UTC()); err != nil {
			t.Fatal(err)
		}
		_, err := service.DeleteLine(ctx, repository.document.ID, repository.document.LineItems[0].ID, repository.document.Version)
		if !hasCode(err, buhari.CodeDocumentFinalized) {
			t.Fatalf("error = %v", err)
		}
	})

	t.Run("archived", func(t *testing.T) {
		service, repository, ctx := newLineService(t, 1)
		if err := repository.document.Archive(time.Now().UTC()); err != nil {
			t.Fatal(err)
		}
		_, err := service.AddLine(ctx, repository.document.ID, repository.document.Version, calculations.LineInput{Description: "Added", Quantity: 1})
		if !hasCode(err, buhari.CodeDocumentArchived) {
			t.Fatalf("error = %v", err)
		}
	})

	t.Run("stale version", func(t *testing.T) {
		service, repository, ctx := newLineService(t, 1)
		_, err := service.DeleteLine(ctx, repository.document.ID, repository.document.LineItems[0].ID, repository.document.Version+1)
		if !hasCode(err, buhari.CodeDocumentVersionConflict) {
			t.Fatalf("error = %v", err)
		}
	})

	t.Run("different owner", func(t *testing.T) {
		service, repository, _ := newLineService(t, 1)
		otherCtx := requestctx.WithExecutor(context.Background(), model.Executor{ID: model.UserID(lid.NewUser()), Role: "user"})
		_, err := service.DeleteLine(otherCtx, repository.document.ID, repository.document.LineItems[0].ID, 1)
		if !hasCode(err, buhari.CodeNotFound) {
			t.Fatalf("error = %v", err)
		}
	})
}

func TestDocumentServiceReorderLines(t *testing.T) {
	service, repository, ctx := newLineServiceWithInputs(t, []calculations.LineInput{
		{Description: "Fixed discount", Quantity: 2, UnitPriceMinor: 2_000, Discount: &calculations.Discount{Type: calculations.DiscountFixed, Value: 500}, TaxRate: 50_000},
		{Description: "Percentage discount", Quantity: 3, UnitPriceMinor: 1_000, Discount: &calculations.Discount{Type: calculations.DiscountPercentage, Value: 100_000}, TaxRate: 200_000},
		{Description: "Untaxed", Quantity: 1, UnitPriceMinor: 750},
	})
	beforeTotals := repository.document.Totals
	beforeTaxBreakdown := append([]calculations.TaxBreakdown(nil), repository.document.TaxBreakdown...)
	ids := []string{repository.document.LineItems[2].ID, repository.document.LineItems[0].ID, repository.document.LineItems[1].ID}
	result, err := service.ReorderLines(ctx, repository.document.ID, 1, ids)
	if err != nil {
		t.Fatal(err)
	}
	for index, id := range ids {
		if result.LineItems[index].ID != id {
			t.Fatalf("line %d ID=%s want=%s", index, result.LineItems[index].ID, id)
		}
	}
	if result.Version != 2 {
		t.Fatalf("version = %d", result.Version)
	}
	if result.Totals != beforeTotals {
		t.Fatalf("reorder changed totals: before=%+v after=%+v", beforeTotals, result.Totals)
	}
	if !reflect.DeepEqual(result.TaxBreakdown, beforeTaxBreakdown) {
		t.Fatalf("reorder changed tax breakdown: before=%+v after=%+v", beforeTaxBreakdown, result.TaxBreakdown)
	}
}

func TestDocumentServicePreviewDoesNotPersistOrAllocateReference(t *testing.T) {
	service, repository, references, ctx := newLineServiceDependencies(t, nil)
	result, err := service.Preview(ctx, CalculationPreviewInput{
		Currency:  model.CurrencyUSD,
		LineItems: []calculations.LineInput{{Description: "Preview", Quantity: 2, UnitPriceMinor: 500, TaxRate: 100_000}},
	})
	if err != nil {
		t.Fatal(err)
	}
	if result.Totals.GrandTotalMinor != 1_100 {
		t.Fatalf("preview totals = %+v", result.Totals)
	}
	if repository.createCalls != 0 || repository.replaceCalls != 0 || references.allocations != 0 {
		t.Fatalf("preview had side effects: creates=%d replacements=%d allocations=%d", repository.createCalls, repository.replaceCalls, references.allocations)
	}
	_, err = service.Preview(ctx, CalculationPreviewInput{Currency: model.Currency("BTC")})
	if !hasCode(err, buhari.CodeValidationFailed) {
		t.Fatalf("invalid currency error = %v", err)
	}
}

func TestDocumentServiceUsesLifecycleSpecificErrors(t *testing.T) {
	t.Run("finalize already finalized", func(t *testing.T) {
		service, repository, _, ctx := newLineServiceDependencies(t, []calculations.LineInput{{Description: "Line", Quantity: 1}})
		if err := repository.document.Finalize(time.Now().UTC()); err != nil {
			t.Fatal(err)
		}
		_, err := service.Finalize(ctx, repository.document.ID, repository.document.Version)
		if !hasCode(err, buhari.CodeDocumentAlreadyFinalized) {
			t.Fatalf("finalize error = %v", err)
		}
		if repository.replaceCalls != 0 {
			t.Fatalf("finalize persisted %d times", repository.replaceCalls)
		}
	})

	t.Run("duplicate source draft", func(t *testing.T) {
		service, repository, references, ctx := newLineServiceDependencies(t, nil)
		_, err := service.Duplicate(ctx, repository.document.ID, DuplicateDocumentInput{})
		if !hasCode(err, buhari.CodeSourceDocumentNotFinalized) {
			t.Fatalf("duplicate error = %v", err)
		}
		if repository.createCalls != 0 || references.allocations != 0 {
			t.Fatalf("duplicate had side effects: creates=%d allocations=%d", repository.createCalls, references.allocations)
		}
	})
}

func TestDocumentServiceRejectsInvalidLineOrder(t *testing.T) {
	service, repository, ctx := newLineService(t, 2)
	firstID := repository.document.LineItems[0].ID
	tests := [][]string{{firstID}, {firstID, firstID}, {firstID, lid.NewLine()}}
	for _, order := range tests {
		if _, err := service.ReorderLines(ctx, repository.document.ID, 1, order); !hasCode(err, buhari.CodeInvalidLineOrder) {
			t.Fatalf("order=%v error=%v", order, err)
		}
	}
	if repository.replaceCalls != 0 {
		t.Fatalf("replace calls = %d", repository.replaceCalls)
	}
}

type lineDocumentRepository struct {
	document     model.Document
	createCalls  int
	listCalls    int
	replaceCalls int
}

var _ mercury.Documents = (*lineDocumentRepository)(nil)

func (repository *lineDocumentRepository) Create(_ context.Context, document model.Document) error {
	repository.createCalls++
	repository.document = document
	return nil
}
func (repository *lineDocumentRepository) FindByReference(context.Context, string, string) (model.Document, error) {
	return model.Document{}, buhari.New(buhari.CodeNotFound, "Document not found.")
}
func (repository *lineDocumentRepository) List(context.Context, string, mercury.DocumentListFilter) (mercury.DocumentPage, error) {
	repository.listCalls++
	return mercury.DocumentPage{}, nil
}
func (repository *lineDocumentRepository) FindByID(_ context.Context, ownerID, documentID string) (model.Document, error) {
	if ownerID != repository.document.OwnerID || documentID != repository.document.ID {
		return model.Document{}, buhari.New(buhari.CodeNotFound, "Document not found.")
	}
	return repository.document, nil
}
func (repository *lineDocumentRepository) ReplaceDraft(_ context.Context, document model.Document, expectedVersion int64) error {
	if repository.document.Version != expectedVersion {
		return buhari.New(buhari.CodeDocumentVersionConflict, "Document was changed by another request.")
	}
	repository.replaceCalls++
	repository.document = document
	return nil
}
func (repository *lineDocumentRepository) Finalize(ctx context.Context, document model.Document, version int64) error {
	return repository.ReplaceDraft(ctx, document, version)
}
func (repository *lineDocumentRepository) Archive(ctx context.Context, document model.Document, version int64) error {
	return repository.ReplaceDraft(ctx, document, version)
}
func (repository *lineDocumentRepository) Restore(ctx context.Context, document model.Document, version int64) error {
	return repository.ReplaceDraft(ctx, document, version)
}

type lineReferenceRepository struct{ allocations int }

func (repository *lineReferenceRepository) Allocate(context.Context, string, int, time.Time) (string, error) {
	repository.allocations++
	return "DOC-2026-000002", nil
}

func newLineService(t *testing.T, lineCount int) (*DocumentService, *lineDocumentRepository, context.Context) {
	t.Helper()
	lines := make([]calculations.LineInput, lineCount)
	for index := range lines {
		lines[index] = calculations.LineInput{Description: "Line", Quantity: 1, UnitPriceMinor: 1_000}
	}
	return newLineServiceWithInputs(t, lines)
}

func newLineServiceWithInputs(t *testing.T, lines []calculations.LineInput) (*DocumentService, *lineDocumentRepository, context.Context) {
	t.Helper()
	service, repository, _, ctx := newLineServiceDependencies(t, lines)
	return service, repository, ctx
}

func newLineServiceDependencies(t *testing.T, lines []calculations.LineInput) (*DocumentService, *lineDocumentRepository, *lineReferenceRepository, context.Context) {
	t.Helper()
	ownerID := lid.NewUser()
	document, err := model.NewDocument(ownerID, "DOC-2026-000001", model.DocumentInput{
		Title: "Line service", Customer: "Acme Limited",
		IssueDate: time.Date(2026, 8, 8, 0, 0, 0, 0, time.UTC), Currency: model.CurrencyUSD, LineItems: lines,
	}, time.Date(2026, 8, 8, 10, 0, 0, 0, time.UTC))
	if err != nil {
		t.Fatal(err)
	}
	repository := &lineDocumentRepository{document: document}
	references := &lineReferenceRepository{}
	service, err := NewDocumentService(repository, references)
	if err != nil {
		t.Fatal(err)
	}
	ctx := requestctx.WithExecutor(context.Background(), model.Executor{ID: model.UserID(ownerID), Role: "user"})
	return service, repository, references, ctx
}
